### ISSUE TITLE
Use KDE 5.9 runtime?

### ISSUE THREAD

**Issue by nedrichards** [knapsu/plex-media-player-flatpak#1]
Based on the information in the readme at https://github.com/plexinc/plex-media-player upstream really wants you to use Qt 5.9.x. Given that, you should probably use the KDE 5.9 runtime, which is still available from flathub. It's not built on the more modern 18.08 Freedesktop SDK but being able to fix these kinds of things is kind of why flatpak was designed the way it was.

Otherwise, cool project.

**Comment by knapsu** [comment]
You are right. Switched back to Qt 5.9 as suggested. Commit 5e9360b596b1003d638de7f8ea4e29712b06ea59
