### ISSUE TITLE
travis-ci.org is no longer building builds

### ISSUE THREAD

**Issue by trammel** [knapsu/plex-media-player-flatpak#11]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

travis-ci.org is no longer building. If you wish to continue using travis, there's a migration procedure to go through to move the builds to travis-ci.com

But until a new solution is found, the fixes (thank you) won't be automatically published to your repo and made available to the public.

**Comment by knapsu** [comment]
Hi @trammel. My first try to migrate from .org to .com was fruitless as my GitHub repos were not visible for some reason. Will retry this and go through the guide you linked to. :+1:

**Comment by knapsu** [comment]
Instead of migrating to Travis CI (.com) I've decided to go with Github Actions. This is mostly because it is a native solution.
