### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by wyphan** [knapsu/plex-media-player-flatpak#12]
I'm trying to run Plex media player version 2.58.1-ae73e074 on Ubuntu 20.04.3 LTS. It crashes on startup with the following error message:
```
Cannot load libcuda.so.1
```

For me, this is a weird error because I'm running the flatpak app on an Intel laptop with only an integrated GPU (no NVIDIA GPU!).
I did install the CUDA Toolkit a while back for work-related code development, but isn't flatpak meant to be a sandbox so it shouldn't rely on the existence of that particular CUDA library file in the actual system directories (`/usr/local/cuda`)?

The full error that I see on standard output when launching the app manually with `flatpak run tv.plex.PlexMediaPlayer` from the terminal can be seen here:
https://gist.github.com/wyphan/fef0c23c90c97e7f462e4aee89ed7c51

Please let me know if I can upload more detailed crash logs, and where I should be able to find/generate them.

**Comment by wyphan** [comment]
Also, this might be a duplicate of #8. Please feel free to close this issue, and I'll comment on #8, if it truly is a duplicate.
Edit: wording

**Comment by knapsu** [comment]
@wyphan There is a new Flatpak package of the app with Qt 5.15 and disabled NVIDIA CUDA libraries. If possible please check it out to see if error is gone.

```
flatpak update
flatpak run tv.plex.PlexMediaPlayer
```

**Comment by wyphan** [comment]
Yes, that fixed it! You can close the issue.

**Comment by knapsu** [comment]
Happy to hear that. Take care!
