### ISSUE TITLE
Official Plex packages available

### ISSUE THREAD

**Issue by davidmartos96** [knapsu/plex-media-player-flatpak#16]
Hello!
This is not really an issue report. I just wanted to let you know that an official Plex version is available in Flathub and as a Snap. https://flathub.org/apps/details/tv.plex.PlexDesktop
https://snapcraft.io/plex-desktop

Just in case you want to update your website or the README.

Thank you for the great flatpak in this repo, I've been using it for a long time as an alternative :smile:

**Comment by knapsu** [comment]
Hi! Thanks for the suggestion. **Plex for Linux** app is now advertised as the replacement in both GitHub repositories and on my website.
