### ISSUE TITLE
Display goes to sleep on Ubuntu 19.10 

### ISSUE THREAD

**Issue by tugboat-maguire** [knapsu/plex-media-player-flatpak#2]
I am using the flatpak version and my display will turn off when I am watching something on pmp.

My screen turns off after 5 minutes as set by the blank screen settings: https://i.imgur.com/6U7TY50.png. pmp shouldn't allow this to happen. I am using ubuntu on wayland, I am not sure if that matters.

my screen doesn't turn off when watching youtube or netflix.

also, why is it zoomed in so much? https://i.imgur.com/QpXiDzQ.png

**Comment by knapsu** [comment]
Hi. I've just made some improvements to the Flatpak package. Could you install the latest version and check if the screensaver problem still occurs? Also please tell me which Ubuntu version are you using exactly.

_Please note the Flatpak repository address has changed recently._

**Comment by flying-sausages** [comment]
I can confirm that with the new release the screen no longer times out on Ubuntu 20.04.

**Comment by tugboat-maguire** [comment]
Unfortunately, I can't comment on the issue because I've been using the appimage.
 
according to the post above me, it's been fixed. sorry I wish I could help

**Comment by knapsu** [comment]
@cca310 I was hoping you could also confirm this as the issue reporter but if you can't then it's perfectly ok. @flying-sausages says it is fixed so I will close the issue as resolved. Thanks everyone.
