### ISSUE TITLE
CEC not working

### ISSUE THREAD

**Issue by ghost** [knapsu/plex-media-player-flatpak#6]
Hi, I have a issue with internal CEC adapter from pulse eight on my NUC8i5BE with flatpak PMP.
CEC works with PMP app image and kodi but not with flatpac PMP, I prefer flatpak PMP because it can do hardware decoding and app image can’t, is CEC working out of flatpak install or do i need to do anything else?

**Comment by knapsu** [comment]
Hi @Zero0Q. Flatpak apps runs in a sandbox. Unfortunately there are no permissions that allow to expose USB devices that `libCEC` wants to use. That is why it does not work. AppImage on the other hand has no security model and can freely communicate with any device in the system.

I am unable to fix this. Will leave the issue open as maybe in the future this will be possible.

**Comment by ghost** [comment]
Thank you for your help, I guess I will use Appimage instead, do you know if you be adding hardware decoding in Appimage in next release or in the future?

**Comment by knapsu** [comment]
I spend quite a lot of hours trying to add hardware decoding to AppImage. It is enabled but very fragile. On some system it works and on some it does not. Suspecting this is video driver related but was not able to pinpoint the exact problem.

**Comment by ghost** [comment]
I installed Ubuntu 18.04 on NUC8i5BEH running intel iris plus graphics 655 but still no luck.

**Comment by knapsu** [comment]
Intel drivers and their VA-API incompatibilities between _minor_ verions are to blame.
