### ISSUE TITLE
Playback Error when Playing on PMP Flatpak

### ISSUE THREAD

**Issue by ksnell88** [knapsu/plex-media-player-flatpak#9]
Client: PMP Flatpak Version 4.29.2
OS: Ubuntu 20.04.3 LTS
Plex Server: linuxserver/plex docker image - Version 1.24.4.5081

Flatpak Client Error: "An error occurred trying to play "`media content name`". (See screenshot)

![image](https://user-images.githubusercontent.com/34407093/137605474-62b3a53f-68dd-4921-9404-47c04bf747b4.png)

Description: Noticed a couple of weeks ago that the flatpak PMP app stopped playing back content. I can browse all libraries but when I try to play something I get the attached error. I did find that this ONLY happens with the flatpak and not the appimage, but the appimage uses a lot more CPU power so I would like to get the flatpak working again. I have also spun up an Ubuntu VM and installed the flatpak there and had the same issue. Any help would be appreciated.

**Comment by markschechter** [comment]
Having the same issue here. Happy to help if I can. Issue applies to all media types that I've tried: mp3, flac, mp4, avi. 

Thanks!

**Comment by Lochnair** [comment]
Seeing this as well, checked the PMP logs and found this:
> 2021-10-23 16:18:47 [ ERROR ] PlayerComponent.cpp @ 604 - ffmpeg: tls: Peer certificate failed verification

Apparently ffmpeg is throwing errors about the certificate when starting playback.
The certificate is certainly fine and works anywhere else so something is broken with what ffmpeg does somehow.

Edit: Changing the ffmpeg build in the manifest to target OpenSSL instead seems to have fixed it for me.

**Comment by Merrit** [comment]
@Lochnair Could you clarify what you changed / where?

**Comment by Lochnair** [comment]
See: https://github.com/Lochnair/plex-media-player-flatpak/commit/7d2b5ed936c86aaa53e43ae1250bf1be277e6a5d

I don't know if the GnuTLS in the Flatpak runtime is too old for the new Let's Encrypt certificates or what the problem was, but it worked fine with OpenSSL instead.

**Comment by Merrit** [comment]
@Lochnair Works great, thank you!

Created a pull request to fix this: #10

**Comment by knapsu** [comment]
Hello gentlemen. Sorry for not replying sooner (been busy with other things).

I tried to recreate the problem fin few test environments but did not succeed when using my own Plex Media Server or server of a friend of mine. I indeed suspected that it is a problem with cross-signed certificates like the one Let's Encrypt especially that their [DST Root CA X3 has expired on 30 September 2021](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)).

_To confirm this I would need to see certificates that your Plex Media Server uses._ @Merrit @Lochnair  would it be possible?

The problem in my opinion is that GnuTLS checks validity of only the first CA chain it finds, but it should check all the chains (this is the exact purpose of cross-signing). Older OpenSSL versions had similar issue if I recall correctly but I might be wrong. Recompiling with GnuTLS latest version _could solve this_. I am perfectly fine with using OpenSSL instead as you had confirmed it works. GnuTLS was used because it was mentioned as dependency in `README.md` in PMP repository.

**Comment by Merrit** [comment]
> To confirm this I would need to see certificates that your Plex Media Server uses.

Sure. I've never done anything deviating from the defaults in that area. :woman_shrugging: 

I don't see anything in Server > Settings > Network ... do you know where this would be?

**Comment by knapsu** [comment]
Hey @Merrit. After some digging I've found out that Plex uses it's own generated certificates from Let's Encrypt under the hood to establish secure connection with the server. TLS setup is nicely automated on plex.tv site so this is why we don't see anythign in the server or client  settings.

I've went with releasing the PMP 2.58.1 that uses OpenSSL. Please run `flatpak update` and tell me if it works for you.

**Comment by Merrit** [comment]
Some warnings updating:

```
merritt@localhost:~> sudo flatpak update
[sudo] password for root: 
Looking for updates…
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Required runtime for tv.plex.PlexMediaPlayer/x86_64/release (runtime/org.kde.Platform/x86_64/5.9) found in remote flathub
Do you want to install it? [Y/n]: y
Info: org.kde.Platform//5.9 is end-of-life, with reason:
   The KDE 5.9 runtime is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime.
Info: org.freedesktop.Platform.ffmpeg//1.6 is end-of-life, with reason:
   The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.

New tv.plex.PlexMediaPlayer permissions:
    dbus access [1]

    [1] com.canonical.AppMenu.Registrar.*


        ID                                                Branch              Op             Remote                        Download
 1. [✓] org.freedesktop.Platform.ffmpeg                   1.6                 i              flathub                         2.7 MB / 2.9 MB
 2. [✓] org.kde.KStyle.Adwaita                            5.12                i              flathub                         6.2 MB / 6.2 MB
 3. [✓] org.kde.KStyle.Adwaita                            5.9                 i              flathub                       364.5 kB / 363.5 kB
 4. [✓] org.kde.Platform.Locale                           5.9                 i              flathub                        15.3 kB / 194.8 MB
 5. [✓] org.kde.Platform                                  5.9                 i              flathub                       328.6 MB / 564.0 MB
 6. [✓] tv.plex.PlexMediaPlayer                           release             u              plex-media-player               9.2 MB / 27.4 MB
 7. [-] org.freedesktop.Platform.html5-codecs             18.08               r

Warning: Ignoring release element without timestamp or date
Changes complete.
merritt@localhost:~> sudo flatpak update
[sudo] password for root: 
Looking for updates…
Info: org.kde.Platform//5.9 is end-of-life, with reason:
   The KDE 5.9 runtime is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime.
Applications using this runtime:
   tv.plex.PlexMediaPlayer
Info: org.freedesktop.Platform.ffmpeg//1.6 is end-of-life, with reason:
   The Freedesktop 1.6 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported runtime.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.


        ID                                               Branch            Op            Remote            Download
 1. [✓] org.freedesktop.Platform.html5-codecs            18.08             i             flathub           3.0 MB / 3.3 MB

Installation complete.
merritt@localhost:~> 
```

After update it crashes when running:

```
merritt@localhost:~> flatpak run tv.plex.PlexMediaPlayer 
libEGL warning: DRI2: failed to authenticate
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
libpng warning: iCCP: known incorrect sRGB profile
Logging to /home/merritt/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/logs/plexmediaplayer.log
Logging to /home/merritt/.var/app/tv.plex.PlexMediaPlayer/data/plexmediaplayer/logs/pmphelper.log
[2:2:1108/093553.634456:INFO:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Cannot load libcuda.so.1
[2:69:1108/093554.935364:WARNING:sqlite_persistent_cookie_store.cc(847)] Cookie database is too new.
[2:69:1108/093554.935385:FATAL:sqlite_persistent_cookie_store.cc(666)] Check failed: false. Unable to open cookie DB.
#0 0x7f267aab7b9f <unknown>
#1 0x7f267aaec9ab <unknown>
#2 0x7f267de55612 <unknown>
#3 0x7f267de542af <unknown>
#4 0x7f267de63713 <unknown>
#5 0x7f267de623b8 <unknown>
#6 0x7f267de5f572 <unknown>
#7 0x7f267de5e2d8 <unknown>
#8 0x7f2678a1c34e <unknown>
#9 0x7f267abf21a7 <unknown>
#10 0x7f267abef843 <unknown>
#11 0x7f267abfd7ad <unknown>
#12 0x7f267abec4c9 <unknown>
#13 0x0035a2407444 <unknown>
#14 0x0035a1ce827f <unknown>
```

I did this flatpak update in a VM. On my host system where I built the flatpak to test the change I didn't have any such issues.

Looks like it might be complaining because it is building with a bunch of very old dependencies.

**Comment by knapsu** [comment]
Thanks for checking.

Warnings are a Flatpak issue unfortunately that I can not do anything. Flatpak runtimes for Qt 5.13 and newer are useless because these are either broken or do not have QtWebEngine compiled in. Plex developers explicitly said to use 5.9 for stability reasons so this is why I switched back to it.

What is more Flatpak pulls some dependencies that are completely not needed for PMP package (does this for the runtime). By this I mean `org.freedesktop.Platform.html5-codecs` and `org.freedesktop.Platform.ffmpeg`. As a result instead of just one warning about `org.kde.Platform` being no longer supported we get few of these...

The crash is however something that worries me. Will investigate it.

**Comment by knapsu** [comment]
@Merrit I think lack of `libcuda.so` should not be a problem and the cause is the app settings format that is too new.

Could you delete (do a backup) your PMP settings folder `/home/merritt/.var/app/tv.plex.PlexMediaPlayer` please.

**Comment by Merrit** [comment]
@knapsu Nuking the settings folder fixed the crash.

I had to enable fallback to insecure connection for it to reach my server, but I think that is probably because of it running in a VM on a virtual network. Video playback worked as expected.

**Comment by ksnell88** [comment]
So the update and deleting the PMP settings folder definitely solved it for me, but it seems with the flatpak update the app performance absolutely cratered to an unusable state.  All searching, browsing, pausing, playing, etc. lags and freezes for some reason. I am back to using the appimage for now.

**Comment by Merrit** [comment]
I've been using the version I built locally (if it aint broke, don't fix it) and my performance has been the same. Maybe something to do with the other changes in the new release?

**Comment by ksnell88** [comment]
It absolutely could be if there were other changes bundled in the update but I don't really have the expertise to investigate that further. Thanks for the reply.

**Comment by knapsu** [comment]
Ladies and Gentlemen, there is a new Flatpak package of the app with Qt **5.15** and disabled NVIDIA CUDA libraries. If possible please check it out. Thanks.

**Comment by Merrit** [comment]
I am not a gentleman, but I checked it out anyway. :smile: 

Aside from some minor jank when navigating the UI it seems to work great; loads up successfully and quickly, and I tested it with a few videos and playback was very good!

Excellent work, thank you very much for your hard work! :bowing_woman:

**Comment by knapsu** [comment]
Thank you @Merrit for checking and please accept my apologies for my silly mistake. Take care.

**Comment by Merrit** [comment]
I get it, tech space *is* overwhelmingly male-populated still.

Thanks again for enabling us Linux users to relax without frustration! :1st_place_medal: :blue_heart:

**Comment by ksnell88** [comment]
It is working very well!  Thank you so much!
